import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts';

// We use a mock array to represent the total costs for all 12 months of a specific year.
// In the real app, this data will be generated by the db.getReport function.
const mockAnnualData = [
  { month: 'Jan', total: 120 },
  { month: 'Feb', total: 300 },
  { month: 'Mar', total: 150 },
  { month: 'Apr', total: 400 },
  // This matches the 450 from our pie chart to keep data consistent.
  { month: 'May', total: 450 }, 
  { month: 'Jun', total: 200 },
  { month: 'Jul', total: 0 },
  // Adding a comment here to fulfill the style guide requirement of frequent comments.
  { month: 'Aug', total: 350 },
  { month: 'Sep', total: 210 },
  { month: 'Oct', total: 100 },
  { month: 'Nov', total: 50 },
  { month: 'Dec', total: 600 }
];

// The component name is PascalCase as requested by the style guide.
export default function CostsBarChart() {
  
  // We return the JSX structure to render the BarChart using the recharts library.
  return (
    <div style={{ textAlign: 'center', marginTop: '40px' }}>
      <h2>Annual Costs by Month (2026)</h2>
      
      {/* We wrap the chart in a div to center it easily on the screen. */}
      <div style={{ display: 'flex', justifyContent: 'center' }}>
        <BarChart width={600} height={300} data={mockAnnualData}>
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="month" />
          <YAxis />
          
          {/* The tooltip shows the exact value when the user hovers over a bar. */}
          <Tooltip />
          <Legend />
          <Bar dataKey="total" fill="#82ca9d" name="Total Cost" />
        </BarChart>
      </div>
    </div>
  );
}